services:
  - type: web
    name: user-registration-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: JWT_SECRET_KEY
        value: your-strong-secret-key-here
      - key: FLASK_ENV
        value: production
